import Head from "next/head";

export default function Home({ feeds }) {
  console.log(feeds);
  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 style={{ textAlign: "center" }}>FEEDS</h1>
        <div
          style={{
            display: "flex",
            width: "50vw",
            margin: "30px auto",
            justifyContent: "center",
            flexDirection: "column",
            gap: "20px",
          }}
        >
          {feeds.map((el, i) => (
            <div key={el.id}>
              <b>Feed {i + 1}: </b>
              {el.feed}
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

//server will call that async function
export async function getServerSideProps() {
  const response = await fetch("http://localhost:7980/feeds");
  let data = await response.json();
  return { props: { feeds: data } };
}
