import Head from "next/head";
import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
const Page = ({ blogs = [] }) => {
  const router = useRouter();
  const handleClick = (id) => {
    console.log("visiting page id: /", id);
    router.push(`/${id}`);
  };
  return (
    <>
      <Head>
        <title>Blogs Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {blogs.map((el) => (
          <div key={el.id}>
            {/* <Link href={`/${el.id}`}>{el.title}</Link> */}
            {/* instead of writing with Link it can also be written by using router */}
            <h1 onClick={() => handleClick(el.id)}>{el.title}</h1>
          </div>
        ))}
      </div>
    </>
  );
};

export default Page;

export async function getServerSideProps() {
  let response = await fetch("http://localhost:8080/blogs");
  let data = await response.json();
  return {
    props: { blogs: data },
  };
}
