name: evaluation-rct201-sp3
name: counter_app
# Triggers (events)
on: push
pull_request:
  branches:
    - main
 # functions (what needs to be done)
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Install Node 16
        uses: actions/setup-node@v3 
        with:
          node-version: 16.x
      - name: Install dependencies 
        run: npm i
      - name: build project 
        run: pm run build
      - name: Upload artifact in order to deploy 
        uses: actions/upload-artifact@v2 
        with:
          name: production-files 
          path: /build

deploy:
  name: deploy 
  runs-on: ubuntu-latest 
  needs: build

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v2 
      with:
        name: production-files 
        path: ./build

    - name: Deploy to github pages 
      uses: peaceiris/actions-gh-pages@v3 
      with:
        github_token: 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 
        publish_dir: ./build
